# 1ST **WEEK**

In [3]:
import pandas as pd
task_data = {
    "Student_ID": [301, 302, 303, 304, 305, 306, 307, 308, 309, 310],
    "Name": [
        "Ahmed Hassan",
        "Fatima Noor",
        "Ibrahim Shah",
        "Maryam Raza",
        "Daniyal Khan",
        "Laiba Ahmed",
        "Huzaifa Ali",
        "Eman Tariq",
        "Abdullah Malik",
        "Noor Fatima"
    ],
    "City": [
        "Lahore",
        "Karachi",
        "Islamabad",
        "Multan",
        "Lahore",
        "Peshawar",
        "Karachi",
        "Quetta",
        "Faisalabad",
        "Islamabad"
    ],
    "Course": [
        "Python",
        "Data Analytics",
        "Python",
        "Web Development",
        "Data Analytics",
        "Python",
        "Web Development",
        "Data Analytics",
        "Python",
        "Web Development"
    ],
    "Age": [20, 22, 21, 23, 20, 22, 21, 24, 20, 22],
    "Marks": [84, 91, 76, 68, None, 88, 73, 95, 81, 79],
    "Fee_Paid": ["Yes", "Yes", "No", "Yes", "No", "Yes", "Yes", "Yes", "No", "Yes"]
}

task_df = pd.DataFrame(task_data)
task_df

,Student_ID,Name,City,Course,Age,Marks,Fee_Paid
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes
2,303,Ibrahim Shah,Islamabad,Python,21,76.0,No
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes
4,305,Daniyal Khan,Lahore,Data Analytics,20,NaN,No
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes

In [ ]:
'''    Task 1: DataFrame Basics
     - Display the first five rows
     - Find the number of rows and columns
     - Display all column names and data types  '''

print("First 3 Rows: ")
display(task_df.head())
print("-------------------------------------------")
print("No. of Rows and Columns: ",task_df.shape)
print("-------------------------------------------")
print("Column names and Data Types: ")
display(task_df.dtypes)

First 3 Rows:

   Student_ID          Name       City           Course  Age  Marks Fee_Paid
0         301  Ahmed Hassan     Lahore           Python   20   84.0      Yes
1         302   Fatima Noor    Karachi   Data Analytics   22   91.0      Yes
2         303  Ibrahim Shah  Islamabad           Python   21   76.0       No
3         304   Maryam Raza     Multan  Web Development   23   68.0      Yes
4         305  Daniyal Khan     Lahore   Data Analytics   20    NaN       No

-------------------------------------------
No. of Rows and Columns:  (10, 7)
-------------------------------------------
Column names and Data Types:

Student_ID      int64
Name           object
City           object
Course         object
Age             int64
Marks         float64
Fee_Paid       object
dtype: object

In [ ]:
''' Task 2: Column and Row Selection
- Select only Name and Marks
- Select the first four rows using iloc
- Display the City of the student at index 3 using loc '''
selected_columns=task_df[['Name','Marks']]
display(selected_columns)
print("-------------------------------------------")
print('First 4 Rows: ')
display(task_df.iloc[0:4,:])
print("-------------------------------------------")
display(task_df.loc[3,['City']])

             Name  Marks
0    Ahmed Hassan   84.0
1     Fatima Noor   91.0
2    Ibrahim Shah   76.0
3     Maryam Raza   68.0
4    Daniyal Khan    NaN
5     Laiba Ahmed   88.0
6     Huzaifa Ali   73.0
7      Eman Tariq   95.0
8  Abdullah Malik   81.0
9     Noor Fatima   79.0

-------------------------------------------
First 4 Rows:

   Student_ID          Name       City           Course  Age  Marks Fee_Paid
0         301  Ahmed Hassan     Lahore           Python   20   84.0      Yes
1         302   Fatima Noor    Karachi   Data Analytics   22   91.0      Yes
2         303  Ibrahim Shah  Islamabad           Python   21   76.0       No
3         304   Maryam Raza     Multan  Web Development   23   68.0      Yes

-------------------------------------------

City    Multan
Name: 3, dtype: object

In [ ]:
''' Task 3: Filtering
- Display students with marks greater than or equal to `80`
- Display students from Lahore or Karachi
- Display Python students whose marks are greater than 80  '''
high_scorers=task_df[task_df['Marks']>=80]
display(high_scorers)
print("---------------------------------------------------------------------------")
print("---------------------------------------------------------------------------")
specific_students=task_df[(task_df['City']=='Lahore')|(task_df['City']=='Karachi')]
display(specific_students)
print("---------------------------------------------------------------------------")
print("---------------------------------------------------------------------------")
python_students=task_df[(task_df['Course']=='Python') & (task_df['Marks']>80)]
display(python_students)

   Student_ID            Name        City          Course  Age  Marks Fee_Paid
0         301    Ahmed Hassan      Lahore          Python   20   84.0      Yes
1         302     Fatima Noor     Karachi  Data Analytics   22   91.0      Yes
5         306     Laiba Ahmed    Peshawar          Python   22   88.0      Yes
7         308      Eman Tariq      Quetta  Data Analytics   24   95.0      Yes
8         309  Abdullah Malik  Faisalabad          Python   20   81.0       No

---------------------------------------------------------------------------
---------------------------------------------------------------------------

   Student_ID          Name     City           Course  Age  Marks Fee_Paid
0         301  Ahmed Hassan   Lahore           Python   20   84.0      Yes
1         302   Fatima Noor  Karachi   Data Analytics   22   91.0      Yes
4         305  Daniyal Khan   Lahore   Data Analytics   20    NaN       No
6         307   Huzaifa Ali  Karachi  Web Development   21   73.0      Yes

---------------------------------------------------------------------------
---------------------------------------------------------------------------

   Student_ID            Name        City  Course  Age  Marks Fee_Paid
0         301    Ahmed Hassan      Lahore  Python   20   84.0      Yes
5         306     Laiba Ahmed    Peshawar  Python   22   88.0      Yes
8         309  Abdullah Malik  Faisalabad  Python   20   81.0       No

In [ ]:
''' Task 4: Add and Update Data
- Add a `Bonus_Marks` column equal to 5% of marks
- Update one student's city
- Rename `Fee_Paid` to `Fee_Status`
- Drop the `Bonus_Marks` column after checking it '''
practice_df=task_df.copy()
practice_df['Bonus_Marks']=practice_df['Marks']*0.05

practice_df.loc[2, "City"] = "Rawalpindi"                  # Important & new thing I've learned.

practice_df = practice_df.rename(
    columns={"Fee_Paid":"Fee_Status"})

practice_df=practice_df.drop(columns=['Bonus_Marks'])

display(practice_df)

,Student_ID,Name,City,Course,Age,Marks,Fee_Status
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes
2,303,Ibrahim Shah,Rawalpindi,Python,21,76.0,No
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes
4,305,Daniyal Khan,Lahore,Data Analytics,20,NaN,No
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes

In [ ]:
'''   Task 5: Missing Values
- Count missing values in every column
- Fill missing marks with the average marks
- Confirm that no missing marks remain  '''
print(task_df.isnull().sum())
print("--------------------------------")
task_df['Marks']=task_df['Marks'].fillna(task_df['Marks'].median())
display(task_df)
print("---------------------------------------------------------------------------")
print(task_df.notnull().sum())

Student_ID    0
Name          0
City          0
Course        0
Age           0
Marks         1
Fee_Paid      0
dtype: int64
--------------------------------

,Student_ID,Name,City,Course,Age,Marks,Fee_Paid
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes
2,303,Ibrahim Shah,Islamabad,Python,21,76.0,No
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes
4,305,Daniyal Khan,Lahore,Data Analytics,20,81.0,No
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes

---------------------------------------------------------------------------
Student_ID    10
Name          10
City          10
Course        10
Age           10
Marks         10
Fee_Paid      10
dtype: int64

In [ ]:
'''   Task 6: Sorting and Aggregations
- Sort students by marks from highest to lowest
- Calculate total, average, minimum, and maximum marks
- Find the number of non-missing marks   '''
sorted_df = task_df.sort_values(by='Marks',ascending=False)
display(sorted_df)
print("---------------------------------------------------------------------------")
print("---------------------------------------------------------------------------")
print("Total marks: ",task_df['Marks'].sum())
print("Total marks: ",task_df['Marks'].mean())
print("Total marks: ",task_df['Marks'].min())
print("Total marks: ",task_df['Marks'].max())
print("----------------------------------")
print("----------------------------------")
print("Non-Missing values: ",task_df['Marks'].isnull().sum())

,Student_ID,Name,City,Course,Age,Marks,Fee_Paid
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No
4,305,Daniyal Khan,Lahore,Data Analytics,20,81.0,No
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes
2,303,Ibrahim Shah,Islamabad,Python,21,76.0,No
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes

---------------------------------------------------------------------------
---------------------------------------------------------------------------
Total marks:  816.0
Total marks:  81.6
Total marks:  68.0
Total marks:  95.0
----------------------------------
----------------------------------
Non-Missing values:  0

In [ ]:
'''      Task 7: GroupBy
- Calculate average marks by course
- Count students by city
- Find the highest marks in every course  '''
course_avg = task_df.groupby('Course')['Marks'].mean()
display(course_avg)
print("--------------------------------")
print("--------------------------------")
student_count=task_df.groupby('City')['Student_ID'].count()
display(student_count)
print("-------------------------------")
print("-------------------------------")
course_max_marks = task_df.groupby('Course')['Marks'].max()
display(course_max_marks)

Course
Data Analytics     89.000000
Python             82.250000
Web Development    73.333333
Name: Marks, dtype: float64

--------------------------------
--------------------------------

City
Faisalabad    1
Islamabad     2
Karachi       2
Lahore        2
Multan        1
Peshawar      1
Quetta        1
Name: Student_ID, dtype: int64

-------------------------------
-------------------------------

Course
Data Analytics     95.0
Python             88.0
Web Development    79.0
Name: Marks, dtype: float64

In [ ]:
'''  Task 8: Final Class Challenge
Create a complete student report that:

1. Cleans missing marks
2. Adds a Pass/Fail column
3. Filters students with marks of 80 or more
4. Calculates course-wise average marks
5. Sorts students from highest to lowest marks
6. Exports the final result to CSV and JSON  '''
all_data=print("no need for step 1(coz already cleaned the data before)")
print("-------------------------------------------------------")
print("-------------------------------------------------------")
task_df.loc[2,"Marks"] = 40
task_df["Result"] = task_df["Marks"].apply(lambda x: "Pass" if x >= 45 else "Fail")        # IMP THNGGGGGGGGGGGGGGGGGGGGGGGGGGGG
display(task_df)
print("--------------------------------------------------------------------------------------")
print("--------------------------------------------------------------------------------------")
sorted_df=task_df.sort_values(by='Marks',ascending=False)
display(sorted_df)
sorted_df.to_csv("Final_Student_Report.csv",index=False)
sorted_df.to_json("Final_Student_Report.json",orient="records",indent=4)

no need for step 1(coz already cleaned the data before)
-------------------------------------------------------
-------------------------------------------------------

,Student_ID,Name,City,Course,Age,Marks,Fee_Paid,Result
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes,Pass
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes,Pass
2,303,Ibrahim Shah,Islamabad,Python,21,40.0,No,Fail
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes,Pass
4,305,Daniyal Khan,Lahore,Data Analytics,20,81.0,No,Pass
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes,Pass
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes,Pass
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes,Pass
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No,Pass
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes,Pass

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

,Student_ID,Name,City,Course,Age,Marks,Fee_Paid,Result
7,308,Eman Tariq,Quetta,Data Analytics,24,95.0,Yes,Pass
1,302,Fatima Noor,Karachi,Data Analytics,22,91.0,Yes,Pass
5,306,Laiba Ahmed,Peshawar,Python,22,88.0,Yes,Pass
0,301,Ahmed Hassan,Lahore,Python,20,84.0,Yes,Pass
8,309,Abdullah Malik,Faisalabad,Python,20,81.0,No,Pass
4,305,Daniyal Khan,Lahore,Data Analytics,20,81.0,No,Pass
9,310,Noor Fatima,Islamabad,Web Development,22,79.0,Yes,Pass
6,307,Huzaifa Ali,Karachi,Web Development,21,73.0,Yes,Pass
3,304,Maryam Raza,Multan,Web Development,23,68.0,Yes,Pass
2,303,Ibrahim Shah,Islamabad,Python,21,40.0,No,Fail

# 2ND **WEEK**

*Level 1: DataFrame & Series Basics*

1. *Create*: Make a DataFrame with columns `Name`, `Age`, `City` for 5 students.
2. *Read*: Load a CSV file `students.csv` into a DataFrame.
3. *View*: Show first 3 rows and last 2 rows of the DataFrame.
4. *Info*: Print column names, data types, and shape of the DataFrame.
5. *Select*: Get only the `Name` and `Age` columns from the DataFrame

In [6]:
# Create a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 19, 22, 17],
    "City": ["Karachi", "Los Angeles", "Karachi", "Houston", "Phoenix"]
}
student_df = pd.DataFrame(data)

# Read the CSV file
#df = pd.read_csv("students.csv")  [dont have students.csv file that's why i commented this line of code]
display(student_df.head(3))
print("-------------------------")
display(student_df.tail(2))
print("-------------------------")
print("Column names: ",student_df.columns.tolist())
print("---------------------------------")
print("data types: ",student_df.dtypes)
print("---------------------------------")
print("data types: ",student_df.shape)
display(student_df[["Name","Age"]])

      Name  Age         City
0    Alice   20      Karachi
1      Bob   21  Los Angeles
2  Charlie   19      Karachi

-------------------------

    Name  Age     City
3  David   22  Houston
4    Eva   17  Phoenix

-------------------------
Column names:  ['Name', 'Age', 'City']
---------------------------------
data types:  Name    object
Age      int64
City    object
dtype: object
---------------------------------
data types:  (5, 3)

      Name  Age
0    Alice   20
1      Bob   21
2  Charlie   19
3    David   22
4      Eva   17


*Level 2: Indexing & Filtering*
6. *Filter*: Show all rows where `Age > 20`.
7. *Filter*: Show students who live in `Karachi`.
8. *loc/iloc*: Get the data of the 3rd student using `iloc`.
9. *Add Column*: Add a new column `Passed` with True/False based on marks > 50.
10. *Drop*: Remove the `City` column from the DataFrame.

In [5]:

display(student_df[student_df["Age"]>20])
print("---------------------------------")
display(student_df[student_df["City"]=='Karachi'])
print("---------------------------------")
third_student_data= student_df.iloc[2,:]
display(third_student_data)
print("---------------------------------")
#  student_df["Passed"]=student_df["Marks"].apply(lambda x: "true" if x < 50 else "false")
#   marks columns isn't in our dataframe that's why i've commented this line
updated_student_df=student_df.drop(columns=["City"])
display(updated_student_df)

    Name  Age         City
1    Bob   21  Los Angeles
3  David   22      Houston

---------------------------------

      Name  Age     City
0    Alice   20  Karachi
2  Charlie   19  Karachi

---------------------------------

Name    Charlie
Age          19
City    Karachi
Name: 2, dtype: object

---------------------------------

      Name  Age
0    Alice   20
1      Bob   21
2  Charlie   19
3    David   22
4      Eva   20

*Level 3: Operations & Stats*
11. *Missing Values*: Count how many missing values are in each column. Fill them with 0.
12. *Sort*: Sort the DataFrame by `Age` in descending order.
13. *Stats*: Find the average, max, and min `Age` of students.
14. *GroupBy*: Group by `City` and find average `Age` for each city.
15. *Unique*: How many unique cities are in the DataFrame?

In [ ]:
print(student_df.isnull().sum())
student_df.fillna(0)
sorted_stu_df=student_df.sort_values(by="Age",ascending=False)
display(sorted_stu_df)
print("----------------------------")
print("avg of age: ",student_df["Age"].mean())
print("avg of age: ",student_df["Age"].max())
print("avg of age: ",student_df["Age"].min())
print("--------------------")
city_avg_age = student_df.groupby('City')["Age"].mean()
display(city_avg_age)
print("--------------------")
unique_cities = student_df["City"].unique()
print("Unique Cities of Dataframe: ",unique_cities)

Name    0
Age     0
City    0
dtype: int64

      Name  Age         City
3    David   22      Houston
1      Bob   21  Los Angeles
0    Alice   20      Karachi
4      Eva   20      Phoenix
2  Charlie   19      Karachi

----------------------------
avg of age:  20.4
avg of age:  22
avg of age:  19
--------------------

City
Houston        22.0
Karachi        19.5
Los Angeles    21.0
Phoenix        20.0
Name: Age, dtype: float64

--------------------
Unique Cities of Dataframe:  ['Karachi' 'Los Angeles' 'Houston' 'Phoenix']

*Level 4: Mini Projects*
16. *CSV Save*: After filtering students with `Age < 18`, save them to a new CSV `minors.csv`.
17. *Merge*: Create 2 DataFrames
`students` and `marks`. Merge them on `Name`.
18. *Rename*: Rename column `City` to `Location`.
19. *Apply*: Create a column `Age_Group` = "Adult" if Age >= 18 else "Minor".
20. *Describe*: Use `.describe()` to get summary stats for numeric columns.

In [21]:
filtered_df = student_df[student_df["Age"]<18]
filtered_df.to_csv("minors.csv",index=False)

students = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara", "Ayesha", "Usman"],
    "Age": [15, 21, 19, 22, 17],
    "City": ["Karachi", "Lahore", "Islamabad", "Karachi", "Peshawar"]
})
marks = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara", "Ayesha", "Usman"],
    "Marks": [85, 92, 78, 88, 95]
})
merge_df=pd.merge(students,marks, on="Name")
merge_df=merge_df.rename(columns={"City":"Location"})
merge_df["Age_Group"]=merge_df["Age"].apply(lambda x:"Adult" if x>= 18 else "Minor")
display(merge_df)
display(merge_df.describe(include="all").round(1))

     Name  Age   Location  Marks Age_Group
0     Ali   15    Karachi     85     Minor
1   Ahmed   21     Lahore     92     Adult
2    Sara   19  Islamabad     78     Adult
3  Ayesha   22    Karachi     88     Adult
4   Usman   17   Peshawar     95     Minor

       Name   Age Location  Marks Age_Group
count     5   5.0        5    5.0         5
unique    5   NaN        4    NaN         2
top     Ali   NaN  Karachi    NaN     Adult
freq      1   NaN        2    NaN         3
mean    NaN  18.8      NaN   87.6       NaN
std     NaN   2.9      NaN    6.6       NaN
min     NaN  15.0      NaN   78.0       NaN
25%     NaN  17.0      NaN   85.0       NaN
50%     NaN  19.0      NaN   88.0       NaN
75%     NaN  21.0      NaN   92.0       NaN
max     NaN  22.0      NaN   95.0       NaN